### ISSUE TITLE
Scoped styles

### ISSUE THREAD

**Issue by reegodev** [ParadeTo/vue-date-range#25]
Any chance to have styles scoped to avoid collision with outer CSS? Some class names are quite common like .cell and .selected and they currently override some of my app global styles

**Comment by 105th** [comment]
@ParadeTo seems like you forget to make build of your changes, because even if install last version from npm, it apply style for ".selected" class.

Also, you forget to change version in package.json and change readme in [custom-style section ](https://github.com/ParadeTo/vue-date-range#custom-style)

**Comment by 105th** [comment]
@ParadeTo and also you has made a mistake [here](https://github.com/ParadeTo/vue-date-range/commit/47cadd7b8965cf60e6714bf062e52b264631174c#diff-668f2fe5b32e9422b5da73784f9d6675R11)

**Comment by ParadeTo** [comment]
@105th Thank you! I made so much mistakes!!!!

**Comment by TahiriAbdou** [comment]
@ParadeTo any chance to use Scoped styles ? or to just disable animation because the vue animation is overriding my app animation.

**Comment by ParadeTo** [comment]
The styles problem is so annoying.

**Comment by TahiriAbdou** [comment]
Am not fully sure, but this styles can do a conflict as well.
why don't you consider scoped styles ?

**Comment by ParadeTo** [comment]
@TahiriAbdou Because I want user can modify the style
